#standalone run

###build
FROM golang:1.16-alpine AS builder
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o main ./cmd/api
WORKDIR /app
RUN cp /build/main .

###release
FROM alpine:3.13
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8081
CMD ["/app/main"]